### ISSUE TITLE
nimbits loses values it they come very quickly and filter is set

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#181] opened 2016-10-26 21:01 UTC
Seems it is caused due to processing on server by different threads.

**Comment by bsautner** [comment] 2016-10-27 12:10
can you let me know what nimbits.io methods you're using to write your data?

**Comment by nikolchina** [comment] 2016-10-27 12:13
recordValue(String pointName, Value value)

**Comment by bsautner** [comment] 2016-10-27 12:19
thanks - if I created a method such as 

`recordValues(String pointName, List<Value> newValues)`

would that an option for you?  Posting your values in a batch would avoid this race condition.  It's what the batch processing api is meant for.

**Comment by nikolchina** [comment] 2016-10-27 12:41
such method can be useful if we get our events from database and resend them to nimbits. But it is not applicable at all when events occur very quickly because we are not able to store these events in list before sending to nimbits.

**Comment by bsautner** [comment] 2016-10-27 12:43
ok we'll figure something out for you

**Comment by bsautner** [comment] 2016-10-27 13:04
Is the test you're running behind the load balancer?  I'm wondering if the issue is related to different instance of numbers processing the data.

**Comment by nikolchina** [comment] 2016-10-27 13:18
we don't use any balancer so far

**Comment by bsautner** [comment] 2016-10-27 17:41
to reproduce this, I'd need to write a repeating sequence of 0 and 1 at a high frequency in order to get the system to fall behind and process them out of order - is that correct?  What are the filter settings you have on the data point when this happens?

**Comment by nikolchina** [comment] 2016-10-27 19:06
0.9 Fixed Hysteresis

**Comment by nikolchina** [comment] 2016-10-27 19:10
yes, our system sends 1, 0, 1, 0, 1, 0

**Comment by bsautner** [comment] 2016-10-27 19:57
ok makes sense.  I reproduced it in a test here.  I was able to prevent this from happening by putting a Thread.sleep(10) so values came in at a rate the system would process.  But I understand that's not ideal.

**Comment by bsautner** [comment] 2016-11-06 18:43
resolved with sync api impl

**Closed by bsautner** 2016-11-06 18:43 UTC
